### PR TITLE
Add fluid_player_get_status and fix some typing bugs

### PR DESCRIPTION
**Pull request by Fruchtzwerg94**
Fixed the data type for synth.sample rate according to the [documentation](https://www.fluidsynth.org/api/settings_synth.html) to float.
This removes the error:
grafik

Also:

- added fluid_player_get_status
- fixed int return for fluid_player_add

### CODE REVIEW

**Review by filipeborato — APPROVED** [review]

**Comment by trenslow** [comment]
@filipeborato any chance we can get these changes released in the near future?

**Comment by filipeborato** [comment]
@trenslow I don't have the power to merge, but I tested it and it looks ok.

**Comment by albedozero** [comment]
Thanks! Sorry to take so long to get to this. I changed the title to reflect the adding of a new function binding, since this is a bigger change than bugfixes.

fixes https://github.com/nwhitehead/pyfluidsynth/issues/37

**Comment by trenslow** [comment]
Thanks a million @albedozero! I appreciate the work you guys are doing on this project.

**Comment by TombCrawler** [comment]
I've done all the change by [Fruchtzwerg94 but still got the same issue. Anyone?

**Pull request merged**
